### ISSUE TITLE
nick.exit() terminate caller process

### ISSUE THREAD

**Issue by meepeek** [phantombuster/nickjs#27]
As the following code, last console.log should be printed but the app would be forced exit as nick.exit() called. By remove nick.exit() line, console.log print the result but the app would not end as it should be. (I will have to Ctrl-c to terminate)

```
const nick = new Nick()
let tab = await nick.newTab()
await tab.open(url)
await tab.untilVisible('.tbl')
let content = await tab.getContent()

nick.exit()

console.log('This line should be printed with content', content)
```

**Comment by paps** [comment]
This is by design, see for example issue #26 (basically `nick.exit()` calls `process.exit()`)

What you can do is close your tabs with `tab.close()`. NickJS doesn't come with the ability to stop Chrome unfortunately. It's automatically killed on exit.

Why do you need to exit NickJS but continue the script?

**Comment by meepeek** [comment]
I just concern that it may cause memory leak if I didn’t close properly since I ran a cron job. By not call exit, no problem so far.

Thanks for the reply

**Comment by paps** [comment]
Yes it shouldn't be a problem. Chrome is automatically terminated when the node process exits
